typography_spectrum: 0.011087515391409397
color:
  brandStrength: 0.8450713292695582
  lightness: 0.4755160193890333
  saturation: 0.6713670247700065
  rhythmicContrast: 0.683130697812885
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.4029858831781894
name: Magnum Opus Digital Entertainment
navigation:
  - name: About Us
    url: 'http://www.magnumopusdigital.net/about-us.html'
    type: external
title: Digital Solutions
description: Audio - Video - Patio Music - High End Landscape Lighting
